name: Build TrueKris Kernel A23

on:
  workflow_dispatch:

jobs:
  build-kernel:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Kernel Source
        uses: actions/with@v4
        with:
          repository: ${{ github.repository }}

      - name: Setup Build Environment
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential bc gcc-aarch64-linux-gnu gcc-arm-linux-gnueabi libssl-dev libfl-dev curl wget zip cpio

      - name: Download Proton Clang
        run: |
          mkdir -p $GITHUB_WORKSPACE/clang
          wget -qO- https://github.com/kdrag0n/proton-clang/archive/master.tar.gz | tar -xz -C $GITHUB_WORKSPACE/clang --strip-components=1

      - name: Build the Kernel
        run: |
          export PATH="$GITHUB_WORKSPACE/clang/bin:$PATH"
          export ARCH=arm64
          export SUBARCH=arm64
          export CROSS_COMPILE=aarch64-linux-gnu-
          export CROSS_COMPILE_ARM32=arm-linux-gnueabi-
          export CC=clang
          
          # Очистка перед компиляцией
          make O=out mrproper
          
          # Твой новый именной конфиг!
          make O=out truekris_defconfig
          
          # Запуск сборки на всех доступных ядрах сервера
          make O=out -j$(nproc --all)

      - name: Upload Kernel Image
        uses: actions/upload-artifact@v4
        with:
          name: TrueKris-Kernel-Image
          path: out/arch/arm64/boot/Image*
